### ISSUE TITLE
Dismiss barHow to dismiss bar when changing tab?

### ISSUE THREAD

**Issue by mikelantzelo** [radusalagean/info-bar-compose#1]
I want to show a bar in tabs layout. How to dismiss bar when changing tab? (jetpack compose)

**Comment by radusalagean** [comment]
Hey there. If you're using Tabs together with the Pager from the [accompanist](https://google.github.io/accompanist/pager/) library, you can react to page changes like this:
```kotlin
LaunchedEffect(pagerState) {
    // Collect from the pager state a snapshotFlow reading the currentPage
    snapshotFlow { pagerState.currentPage }.collect {
        message = null
    }
}
```
This will get called regardless if the page is changed by swiping the pager or by selecting a tab.
There, you can set the `message` to null, that will dismiss the `InfoBar`.

**Comment by mikelantzelo** [comment]
Thank you!
